export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export CLICOLOR=1
export EDITOR=vim

# Git Stuff
alias gst='git status'
alias gco='git checkout'
alias vimbi='vim +BundleInstall +qall'
alias bi='bundle install'
alias ge='goop exec'
alias ls='mc ls'
alias cp='mc cp'

# Git Prompt
function parse_git_dirty {
  if ! [[ $(git status 2> /dev/null | tail -n1) =~ "nothing to commit" ]] ; then echo "*"; fi
}

function parse_git_branch {
  git branch --no-color 2> /dev/null | sed -e '/^[^*]/d' -e "s/* \(.*\)/[\1$(parse_git_dirty)]/"
}

export PS1='\u:\[\033[31;40m\]\w\[\033[0;33m\]$(parse_git_branch)\[\e[0m\]$ '

# tmux
alias tmux="TERM=screen-256color-bce tmux"

# Parallels
alias prlstart="prlctl start 'Ubuntu Linux'"
alias prlstop="prlctl stop 'Ubuntu Linux'"

export GOPATH=~/workspace/gospace
export GOBIN=$GOPATH/bin
export PATH=node_modules/.bin:.bundle/binstubs:$PATH:$GOBIN

source ~/.rvm/scripts/rvm

# To make sure rake is the same as the one used by bundler
# use: http://stackoverflow.com/questions/23287357/already-activated-rake-version-different-than-what-gemfile-requires-prevents-rak
# $ gem install rubygems-bundler
# $ gem regenerate_binstubs

function bootstrap_go_project() {
  if [ $# -ne 2 ]
  then
    echo "Usage bootstrap_go_project GITHUB_USERNAME PROJECT_NAME"
    return
  fi

  dir=$GOPATH/src/github.com/$1/$2
  symlinked_target=$HOME/workspace/$2
  mkdir -p $dir
  echo Created ${dir}

  ln -sf ${dir} ${symlinked_target}
  echo Symlinked ${dir} to ${symlinked_target}
}

# From: http://unix.stackexchange.com/questions/75681/why-do-i-have-to-re-set-env-vars-in-tmux-when-i-re-attach
# Predictable SSH authentication socket location.
SOCK="/tmp/ssh-agent-$USER-screen"
if test $SSH_AUTH_SOCK && [ $SSH_AUTH_SOCK != $SOCK ]
then
    rm -f /tmp/ssh-agent-$USER-screen
    ln -sf $SSH_AUTH_SOCK $SOCK
    export SSH_AUTH_SOCK=$SOCK
fi

export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting
